### PR TITLE
Ez recover errors

### PR DESCRIPTION
**Pull request by superbaddude**
Pull request to add recoverability to kinesis connector

I also modified the logger interface so that the module has a logger instead of each individual structure, and then initialize the module's logger.  This makes it easier to provide your own logger object since you only have to initialize it once in the module, and prevents panics when the user does not initialize the logger.

Let me know what you think.

### CODE REVIEW

**Comment by harlow** [comment]
> I also modified the logger interface so that the module has a logger instead of each individual structure, and then initialize the module's logger. This makes it easier to provide your own logger object since you only have to initialize it once in the module, and prevents panics when the user does not initialize the logger.

Much better. I like it :+1: 

Would you mind squashing down the tiny commits into one commit? I can do it in this branch too before I merge in if thats easier.

**Comment by superbaddude** [comment]
Ya, I should have squashed it, sorry.  I can do it, but probably not until next week. If you'd rather get it out sooner, you can do it in the merge, up to you. 



—

**Comment by harlow** [comment]
> Ya, I should have squashed it, sorry.  I can do it, but probably not until next week. If you'd rather get it out sooner, you can do it in the merge, up to you. 

Sounds good. No rush. Will give me a chance to test it over the weekend too.

**Comment by harlow** [comment]
Sorry, didn't mean to close this. Was trying to rebase it into a few focused commits but its not going so well.

**Comment by harlow** [comment]
@superbaddude could you re-open to `master` and we'll get this merged in.

**Pull request closed without merging**
